---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps.jit.si
  resources:
  - jitsis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.jit.si
  resources:
  - jitsis/finalizers
  verbs:
  - update
- apiGroups:
  - apps.jit.si
  resources:
  - jitsis/status
  verbs:
  - get
  - patch
  - update
