FROM markhobson/maven-chrome:jdk-17
ARG JITSI_VERSION
RUN git clone --depth 1 https://github.com/enna-systems/jitsi-meet-torture.git
WORKDIR jitsi-meet-torture
RUN mvn install -DskipTests -Dcheckstyle.skip

ENTRYPOINT [ "mvn", "test",  "-Dchrome.enable.headless=true", "-Dchrome.disable.sandbox" ]
